# Generated by Django 4.2.3 on 2023-10-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='media_handler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='text', max_length=200, null=True)),
                ('content', models.TextField(default='', max_length=2000, null=True)),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
