# Generated by Django 4.2.3 on 2023-10-29 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='media_handler',
            new_name='media_model',
        ),
    ]
