# Generated by Django 4.2.3 on 2023-10-29 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_rename_media_handler_media_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='text', max_length=200, null=True)),
                ('content', models.TextField(default='', max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PositionTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=-1.0, null=True)),
                ('lng', models.FloatField(default=-1.0, null=True)),
                ('accuracy', models.FloatField(default=-1.0, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='media_model',
        ),
        migrations.AddField(
            model_name='mediamodel',
            name='position_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='media.positiontime'),
        ),
    ]
